package: slimdaxo
version: dev
author: Herbert Leier
supportpage: https://www.codebox.at/

page:
    block:  codebox
    title:  'Slimdaxo'
    perm:   slimdaxo[]
    icon:   rex-icon fa-plug
    subpages:
        slimdaxo_settings:   { pjax: true, title: 'translate:slimdaxo_settings', perm: slimdaxo[] }
        slimdaxo_demo:       { pjax: true, title: 'translate:slimdaxo_demo', perm: slimdaxo[] }

requires:
    packages:
        ycom: '^2.0'
        ycom/auth: '^2.0'
        be_style/customizer: '^2.2.0'
    redaxo: '^5.3.0'
